version: 2

jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: python:2.7.12
        environment:
          CIRCLE_ARTIFACTS: /tmp/test-results
    steps:
      - checkout
      -
        restore_cache:
          name: 依存関係をキャッシュから取得
          keys:
            - PUBLISH_2
      -
        run:
          name: OSの初期設定
          command: |
            apt-get update && apt-get install less zip -y
            pip install awscli twine
      -
        run:
          name: 依存関係のインストール
          command: |
            aws s3 cp s3://gs2-repos/python/publish/${PUBLISH_VERSION}/publish-${PUBLISH_VERSION}.tar.gz ~/ && tar -zxvf ~/publish-${PUBLISH_VERSION}.tar.gz -C ~/
            cp ~/publish-${PUBLISH_VERSION}/python/.pypirc ~/.pypirc
      -
        save_cache:
          name: Publishスクリプトをキャッシュに保存
          key: PUBLISH_2
          paths:
            - ~/publish-${PUBLISH_VERSION}
      -
        deploy:
          command: |
            python setup.py sdist
            if [ "${CIRCLE_BRANCH}" == "develop" ]; then
              twine upload  --repository-url https://test.pypi.org/legacy/ dist/*
            fi
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              twine upload dist/*
            fi
      -
        store_test_results:
          path: $CIRCLE_ARTIFACTS